UniversityManagementSystem/Controllers/DeansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityManagementSystem.Data;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class DeansController : Controller
    {
        private readonly UniversityManagementSysDbContext _context;

        public DeansController(UniversityManagementSysDbContext context)
        {
            _context = context;
        }

        // GET: Deans
        public async Task<IActionResult> Index()
        {
              return _context.Deans != null ? 
                          View(await _context.Deans.ToListAsync()) :
                          Problem("Entity set 'UniversityManagementSysDbContext.Deans'  is null.");
        }

        // GET: Deans/Details/5
        [Authorize(Roles = "Administrator,Dean")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Deans == null)
            {
                return NotFound();
            }

            var dean = await _context.Deans
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dean == null)
            {
                return NotFound();
            }

            return View(dean);
        }

        // GET: Deans/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Deans/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Fname,Lname,Dob,Mail,Phone,Address,Office")] Dean dean)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dean);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Dean record was created";
                return RedirectToAction(nameof(Index));
            }
            return View(dean);
        }

        // GET: Deans/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Deans == null)
            {
                return NotFound();
            }

            var dean = await _context.Deans.FindAsync(id);
            if (dean == null)
            {
                return NotFound();
            }
            return View(dean);
        }

        // POST: Deans/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fname,Lname,Dob,Mail,Phone,Address,Office")] Dean dean)
        {
            if (id != dean.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dean);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DeanExists(dean.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Edit"] = "Dean record was Modified";
                return RedirectToAction(nameof(Index));
            }
            return View(dean);
        }

        // GET: Deans/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Deans == null)
            {
                return NotFound();
            }

            var dean = await _context.Deans
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dean == null)
            {
                return NotFound();
            }

            return View(dean);
        }

        // POST: Deans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Deans == null)
            {
                return Problem("Entity set 'UniversityManagementSysDbContext.Deans'  is null.");
            }
            var dean = await _context.Deans.FindAsync(id);
            if (dean != null)
            {
                _context.Deans.Remove(dean);
            }
            
            await _context.SaveChangesAsync();
            TempData["Edit"] = "Dean record was Deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool DeanExists(int id)
        {
          return (_context.Deans?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

UniversityManagementSystem/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityManagementSystem.Data;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly UniversityManagementSysDbContext _context;

        public DepartmentsController(UniversityManagementSysDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            var universityManagementSysDbContext = _context.Departments.Include(d => d.Dean).Include(d => d.Faculty).Include(d => d.Students).Include(d =>d.DepartmentsCourses);
            return View(await universityManagementSysDbContext.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d => d.Dean)
                .Include(d => d.Faculty)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        [Authorize(Roles = "Administrator,Dean")]
        public IActionResult Create()
        {
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "FullName","Mail");
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "Id", "Name");
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DeanId,FacultyId")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Department was created";
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "Id", department.DeanId);
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "Id", "Id", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Edit/5
        [Authorize(Roles = "Administrator,Dean")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "FullName", department.DeanId);
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "Id", "Name", department.FacultyId);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DeanId,FacultyId")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Edit"] = "Deparment record was Modified";
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "Id", department.DeanId);
            ViewData["FacultyId"] = new SelectList(_context.Faculties, "Id", "Id", department.FacultyId);
            return View(department);
        }

        // GET: Departments/Delete/5
        [Authorize(Roles = "Administrator,Dean")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Departments == null)
            {
                return NotFound();
            }

            var department = await _context.Departments
                .Include(d => d.Dean)
                .Include(d => d.Faculty)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Departments == null)
            {
                return Problem("Entity set 'UniversityManagementSysDbContext.Departments'  is null.");
            }
            var department = await _context.Departments.FindAsync(id);
            if (department != null)
            {
                _context.Departments.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            TempData["Edit"] = "Deparment record was Deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
          return (_context.Departments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

UniversityManagementSystem/Controllers/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UniversityManagementSystem.Data;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{

    public class FacultiesController : Controller
    {
        private readonly UniversityManagementSysDbContext _context;

        public FacultiesController(UniversityManagementSysDbContext context)
        {
            _context = context;
        }

        // GET: Faculties
        public async Task<IActionResult> Index()
        {
            var faculties = await _context.Faculties
         .Include(f => f.Dean)
         .Include(f => f.Departments)
         .Include(f => f.Courses)
         .ToListAsync();

            return View(faculties);
        }

        // GET: Faculties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties
                .Include(f => f.Dean)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        [Authorize(Roles = "Administrator,Dean")]
        public IActionResult Create()
        {
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "FullName", "Mail");
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DeanId,Location,Name")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faculty);
                await _context.SaveChangesAsync();
                TempData["Success"] = "Faculty record was created";
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "Mail", faculty.DeanId);
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        [Authorize(Roles = "Administrator,Dean")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties.FindAsync(id);
            if (faculty == null)
            {
                return NotFound();
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "Mail", faculty.DeanId);
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DeanId,Location,Name")] Faculty faculty)
        {
            if (id != faculty.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faculty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacultyExists(faculty.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                TempData["Edit"] = "Faculty record was Modified";
                return RedirectToAction(nameof(Index));
            }
            ViewData["DeanId"] = new SelectList(_context.Deans, "Id", "Mail", faculty.DeanId);
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        [Authorize(Roles = "Administrator,Dean")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Faculties == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculties
                .Include(f => f.Dean)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Faculties == null)
            {
                return Problem("Entity set 'UniversityManagementSysDbContext.Faculties'  is null.");
            }
            var faculty = await _context.Faculties.FindAsync(id);
            if (faculty != null)
            {
                _context.Faculties.Remove(faculty);
            }
            
            await _context.SaveChangesAsync();
            TempData["Edit"] = "Faculty record was Deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool FacultyExists(int id)
        {
          return (_context.Faculties?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

UniversityManagementSystem/Views/Home/About.cshtml
@{
    // in _layout.cshtml when it takes title, it takes from here
    ViewData["Title"] = "About Us";
}
<div class="m-5">

    <h3 class="text-center">About Us</h3>
    <p class="lead text-center">Welcome to the University Management System, your comprehensive solution for efficient and effective university administration. Our system is designed to streamline processes, enhance communication, and empower university stakeholders with the tools they need to succeed.</p>
    <h3 class="text-center">Our Mission</h3>
    <p class="lead text-center">At the University Management System, our mission is to revolutionize the way universities manage their operations. We aim to provide a user-friendly, integrated platform that facilitates seamless collaboration, enhances productivity, and promotes data-driven decision-making.</p>
    <p class="lead text-center">
        <a asp-controller="Home" asp-action="Privacy" class="btn btn-lg btn-light fw-bold border-white bg-white"><i class="bi bi-shield-check"></i> Privacy</a>
    </p>
    <p class="lead">If you have any questions or concerns, please contact us at &#64;<a href="mailto:administrator@ums.com">Help</a>.</p>

</div>

UniversityManagementSystem/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="~/css/carousel.css" />

<div id="myCarousel" class="carousel slide mb-5 mt-0" data-bs-ride="carousel" data-bs-theme="light">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://www.1stformationsblog.co.uk/wp-content/uploads/2022/09/Shutterstock_1079243414.jpg" class="d-block w-100" />
            <div class="container">
                <div class="carousel-caption text-start">
                    <br /><br /><br />
                    <h1 class="text-end">Apply now</h1>                    
                    <p class="opacity-75 text-end">Take the opportunity. To register, send admin an email.</p>
                    <p class="text-end"> <a class="btn btn-lg btn-primary" asp-area="" asp-controller="Home" asp-action="Register"><b>Sign Up Today</b></a></p>
                    
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://pg.edu.pl/files/zie/styles/artykul_664x445/public/2021-11/%5Bszablon%5D%20aktualno%C5%9Bci%20nowe%20%2811%29_0.webp?itok=FnKv22zs" class="d-block w-100" />
            <div class="container">
                <div class="carousel-caption">
                    <h1>Faculties</h1>
                    <p>Find out more about Faculties.</p>
                    <p><a class="btn btn-lg btn-primary" asp-controller="Faculties" asp-action="Index">Learn more</a></p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://studyinlodz.com.pl/files/public//dla_mieszkanca/edukacja/Szkoly_Wyzsze/studyinlodz/WPiA.JPG" class="d-block w-100" />
            <div class="container">
                <div class="carousel-caption text-end">
                    <h1>Departments.</h1>
                    <p>find out more about</p>
                    <p><a class="btn btn-lg btn-primary" asp-controller="Departments" asp-action="Index">Departments</a></p>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

    <!-- Three columns of text below the carousel -->
   @*     <!-- START THE FEATURETTES -->*@

    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">University's Dean <span class="text-body-secondary">administrative position.</span></h2>
            <p class="lead">The dean of a university is the administrative head of a specific faculty or division within the institution. They oversee academic programs, faculty appointments, and student affairs. They play a vital role in guiding the faculty's direction, fostering academic excellence, and promoting research and educational initiatives within their area of responsibility.</p>
            <p><a class="btn btn-outline-info" asp-controller="Deans" asp-action="Index"><strong>View details &raquo;</strong></a></p>
        </div>
        <div class="col-md-5">
            <img src="https://www.tuck.dartmouth.edu/images/made/uploads/articles/deans-office_1500_1000_70.jpg" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" />
        </div>
    </div>
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">University Faculties <span class="text-body-secondary"></span></h2>
            <p class="lead">
                Each faculty is headed by a dean who oversees the faculty's operations, including curriculum development, faculty appointments, research activities, and student affairs. The faculty is comprised of professors, lecturers, researchers, and support staff who contribute to teaching, research, and administration within their respective fields. Departments within a faculty are responsible for designing and delivering courses, conducting research, and often have their own faculty members and administrative staff.
            </p>
            <p><a class="btn btn-outline-info" asp-controller="Faculties" asp-action="Index"><strong>View details &raquo;</strong></a></p>
        </div>
        <div class="col-md-5">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/University_of_%C5%81%C3%B3d%C5%BA_Philology_Faculty_10.jpg/1200px-University_of_%C5%81%C3%B3d%C5%BA_Philology_Faculty_10.jpg?20150426180840" class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" />
        </div>
    </div>

   @* <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">Oh yeah, it’s that good. <span class="text-body-secondary">See for yourself.</span></h2>
            <p class="lead">Another featurette? Of course. More placeholder content here to give you an idea of how this layout would work with some actual real-world content in place.</p>
        </div>
        <div class="col-md-5 order-md-1">
            <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="var(--bs-secondary-bg)" /><text x="50%" y="50%" fill="var(--bs-secondary-color)" dy=".3em">500x500</text></svg>
        </div>
    </div>*@

    <hr class="featurette-divider">



    @*<hr class="featurette-divider">*@

    <!-- /END THE FEATURETTES -->

</div><!-- /.container -->

UniversityManagementSystem/Views/Home/Register.cshtml
@{
    // in _layout.cshtml when it takes title, it takes from here
    ViewData["Title"] = "Regiister";
}

<!DOCTYPE html>
<html>
<head>
    <title>Student Account Registration</title>
</head>
<body>
    <h1 class="text-center mb-5">New User Account Registration</h1>
    <h3>For registration, please follow in the steps below:</h3>
    <ol class="fs-5">
        <li>Select your study.</li>
        <li>Choose your Faculty/Department.</li>
        <li>Contact the university registration office.</li>
        <li>Get student approval of study and attach it to mail below.</li>
        <li>Follow the link
    <a href="mailto:Administrator@ums.com?subject=Student%20Registration&body=Name%3A%0D%0APrivate%20Mail%3A%0D%0APrivate%20Contact%3A%0D%0AFaculty%3A%0D%0ADepartment%3A%0D%0ADean%3A%0D%0APlease%20include%20a%20copy%20of%20the%20university's%20approval%20of%20the%20study.">Click here</a> to send an email to the Administrator.</li>
    </ol>

    <p class="text-secondary fs-5">
        <b>Remark:</b> In-case you are an Employee attach your employment agreement. <br/> Include the <b>Dean</b> of the following departments and/or faculties in the mail.
    </p>
</body>
</html>